### ISSUE TITLE
Measured pwr 

### ISSUE THREAD

**Issue by nebnes** [mttrb/BeaconOSX#4]
Hi !

What is the measured pwr ? 

thanks

**Comment by mttrb** [comment]
The measured power is defined in the Apple documentation for the `CLBeaconRegion` method `peripheralDataWithMeasuredPower:` as:

> The received signal strength indicator (RSSI) value (measured in decibels) for the device. This value represents the measured strength of the beacon from one meter away and is used during ranging. Specify nil to use the default value for the device.

Basically the devices receiving the signal from the iBeacon need an indication of how powerful the the signal transmitted was in order to calculate the distance to the iBeacon.  The iBeacon provides this as the measured power which is the RSSI of the received signal a metre from the iBeacon.

For simple testing you can set this to any value but the more accurate the value the more accurate the distance estimates will be.
